# Generated by Django 5.0.6 on 2024-06-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_book_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
