# Generated by Django 5.0.6 on 2024-06-05 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_book_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='contact_name',
            new_name='contact_number',
        ),
    ]
